# https://docs.getdbt.com/docs/core/connect-data-platform/profiles.yml

base:

  target: dev
  outputs:  

    dev:
      type: bigquery
      location: US
      method: service-account-json
      project: project-stocks
      dataset: dev-owl-data
      threads: 4
      timeout_seconds: 300
      keyfile: "/home/src/google_credentials.json"

  target: prod
  outputs: 

    prod: 
      type: bigquery
      location: US
      method: service-account-json
      project: project-stocks
      dataset: prod-owl-data
      threads: 4
      timeout_seconds: 300
      keyfile: "/home/src/google_credentials.json"
